// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/api/update-restore/db": {
    params: {};
  };
  "/api/metaCreate/db": {
    params: {};
  };
  "/api/timeout/db": {
    params: {};
  };
  "/api/revert/db": {
    params: {};
  };
  "/api/check/db": {
    params: {};
  };
  "/api/add/db": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/metafield-manage": {
    params: {};
  };
  "/app/export-data": {
    params: {};
  };
  "/app/remove-tags": {
    params: {};
  };
  "/app/add-tags": {
    params: {};
  };
  "/app/history": {
    params: {};
  };
  "/app/faq": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/api/update-restore/db" | "/api/metaCreate/db" | "/api/timeout/db" | "/api/revert/db" | "/api/check/db" | "/api/add/db" | "/auth/login" | "/auth/*" | "/app" | "/app/metafield-manage" | "/app/export-data" | "/app/remove-tags" | "/app/add-tags" | "/app/history" | "/app/faq";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/api.update-restore.db.ts": {
    id: "routes/api.update-restore.db";
    page: "/api/update-restore/db";
  };
  "routes/api.metaCreate.db.ts": {
    id: "routes/api.metaCreate.db";
    page: "/api/metaCreate/db";
  };
  "routes/api.timeout.db.ts": {
    id: "routes/api.timeout.db";
    page: "/api/timeout/db";
  };
  "routes/api.revert.db.ts": {
    id: "routes/api.revert.db";
    page: "/api/revert/db";
  };
  "routes/api.check.db.ts": {
    id: "routes/api.check.db";
    page: "/api/check/db";
  };
  "routes/api.add.db.ts": {
    id: "routes/api.add.db";
    page: "/api/add/db";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/metafield-manage" | "/app/export-data" | "/app/remove-tags" | "/app/add-tags" | "/app/history" | "/app/faq";
  };
  "routes/app.metafield-manage.tsx": {
    id: "routes/app.metafield-manage";
    page: "/app/metafield-manage";
  };
  "routes/app.export-data.tsx": {
    id: "routes/app.export-data";
    page: "/app/export-data";
  };
  "routes/app.remove-tags.tsx": {
    id: "routes/app.remove-tags";
    page: "/app/remove-tags";
  };
  "routes/app.add-tags.tsx": {
    id: "routes/app.add-tags";
    page: "/app/add-tags";
  };
  "routes/app.history.tsx": {
    id: "routes/app.history";
    page: "/app/history";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.faq.tsx": {
    id: "routes/app.faq";
    page: "/app/faq";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/api.update-restore.db": typeof import("./app/routes/api.update-restore.db.ts");
  "routes/api.metaCreate.db": typeof import("./app/routes/api.metaCreate.db.ts");
  "routes/api.timeout.db": typeof import("./app/routes/api.timeout.db.ts");
  "routes/api.revert.db": typeof import("./app/routes/api.revert.db.ts");
  "routes/api.check.db": typeof import("./app/routes/api.check.db.ts");
  "routes/api.add.db": typeof import("./app/routes/api.add.db.ts");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.metafield-manage": typeof import("./app/routes/app.metafield-manage.tsx");
  "routes/app.export-data": typeof import("./app/routes/app.export-data.tsx");
  "routes/app.remove-tags": typeof import("./app/routes/app.remove-tags.tsx");
  "routes/app.add-tags": typeof import("./app/routes/app.add-tags.tsx");
  "routes/app.history": typeof import("./app/routes/app.history.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "routes/app.faq": typeof import("./app/routes/app.faq.tsx");
};